app/models/commissions.py
from mongoengine import Document, StringField, URLField, BooleanField


class CommissionsPage(Document):
    body = StringField(required=True)
    background_image = URLField(required=False)

app/models/main.py
from mongoengine import Document, StringField, URLField, BooleanField


class MainPage(Document):
    header = StringField(required=True)
    body = StringField(required=True)
    button_text = StringField(required=True)
    background_image = URLField(required=False)


class SocialMedia(Document):
    active = BooleanField(default=True)
    link = URLField(required=True)
    icon = URLField(required=True)
    name = StringField(required=False)

app/models/portfolio.py
from mongoengine import Document, StringField, URLField, BooleanField, IntField


class PortfolioPage(Document):
    body = StringField(required=False)
    background_image = URLField(required=False)


class PortfolioImage(Document):
    active = BooleanField(default=True)
    url = URLField(required=True)
    thumbnail_url = URLField(required=False)
    name = StringField(required=False)

app/views/commissions/forms.py
from flask import request

from flask_wtf import FlaskForm
from flask_wtf.file import FileSize, FileField
from wtforms import StringField, EmailField, SubmitField, TextAreaField, MultipleFileField, Form, Field, ValidationError
from wtforms.validators import DataRequired


class ContactUsForm(FlaskForm):
    subject = StringField("subject", validators=[DataRequired()])
    contact = EmailField("email", validators=[DataRequired()])
    body = TextAreaField("body", validators=[DataRequired()])
    references = FileField('Upload your references', validators=[FileSize(2 * 1024 * 1024, message="File is too big. Max upload size: 2 MB")])
    submit = SubmitField()

app/__init__.py
from urllib.parse import urlencode

import dotenv
import flask_bootstrap
from flask import Flask, url_for
from flask_mongoengine import MongoEngine
from flask_wtf import CSRFProtect
from flask_moment import Moment
from flask_mail import Mail

from app.auth import auth
from config import environment_configs

dotenv.load_dotenv()

# bootstrap 4.2.1 supports spinners
flask_bootstrap.BOOTSTRAP_VERSION = "4.2.1"
flask_bootstrap.POPPER_VERSION = "1.14.6"
flask_bootstrap.JQUERY_VERSION = "3.6.0"

mongoengine = MongoEngine()
bootstrap = flask_bootstrap.Bootstrap()
csrf_protect = CSRFProtect()
moment = Moment()
mail = Mail()


def create_app():
    app = Flask(__name__)
    app.config.from_object(f"config.{environment_configs[app.env].__name__}")

    # setting DB connection URL
    mongodb_settings = app.config.get_namespace("MONGODB_")
    mongodb_settings["port"] = f":{mongodb_settings.get('port')}" if mongodb_settings.get("port") else ""
    mongodb_settings["arguments"] = (
        f"?{urlencode(mongodb_settings.get('arguments'))}" if mongodb_settings.get("arguments") else ""
    )
    app.config["MONGODB_HOST"] = "{protocol}://{username}:{password}@{host}{port}/{db}{arguments}".format(
        **mongodb_settings
    )

    app.logger.info(f"Connection to database: {mongodb_settings['db']}")

    bootstrap.init_app(app)
    mongoengine.init_app(app)
    csrf_protect.init_app(app)
    moment.init_app(app)
    mail.init_app(app)
    app.extensions["mail"].debug = 0

    from app.admin import admin_init_app
    admin = admin_init_app(app)

    @app.before_request
    @auth.login_required
    def protect_admin_views():
        pass

    from app.views.main import main_bp
    from app.views.portfolio import portfolio_bp
    from app.views.commissions import commissions_bp
    app.register_blueprint(main_bp)
    app.register_blueprint(portfolio_bp)
    app.register_blueprint(commissions_bp)

    return app

app/admin/__init__.py
from flask import url_for
from flask_admin import Admin

from app import admin
from app.admin.main import MainPageAdminView, SocialMediaAdminView
from app.admin.portfolio import PortfolioImageAdminView, PortfolioPageAdminView
from app.admin.commissions import CommissionsPageAdminView
from app.models.main import MainPage, SocialMedia
from app.models.portfolio import PortfolioImage, PortfolioPage
from app.models.commissions import CommissionsPage

admin = Admin()


class Categories:
    PAGES = "Pages"
    MAIN_PAGE = "Main page"
    PORTFOLIO = "Portfolio"


def admin_init_app(app):
    admin.init_app(app)
    views = (
        MainPageAdminView(MainPage, category=Categories.PAGES, name="Home page"),
        PortfolioPageAdminView(PortfolioPage, category=Categories.PAGES, name="Portfolio"),
        CommissionsPageAdminView(CommissionsPage, category=Categories.PAGES, name="Commissions"),
        SocialMediaAdminView(SocialMedia, category=Categories.MAIN_PAGE, name="Social media"),
        PortfolioImageAdminView(PortfolioImage, category=Categories.PORTFOLIO, name="Images"),
    )

    for view in views:
        admin.add_view(view)

    return admin

app/admin/main.py
from flask_admin.contrib.mongoengine import ModelView

from app.models.main import MainPage, SocialMedia


class MainPageAdminView(ModelView):
    page_size = 10


class SocialMediaAdminView(ModelView):
    page_size = 10

app/auth.py
from flask import current_app, request
from flask_httpauth import HTTPBasicAuth
from werkzeug.security import check_password_hash

from app.admin import admin

auth = HTTPBasicAuth()

@auth.verify_password
def protect_admin_views(username: str, password: str):
    if str(request.url_rule).startswith(admin.url):
        is_username_corrent = username == current_app.config["ADMIN_USERNAME"]
        is_password_correct = check_password_hash(current_app.config["ADMIN_PASSWORD_HASH"], password)
        return username if is_username_corrent and is_password_correct else False
    return True

app/views/commissions/__init__.py
from flask import Blueprint

from app.views.commissions.views import commissions

commissions_bp = Blueprint("commissions", __name__)

commissions_bp.add_url_rule("/commissions", "commissions", commissions, methods=["GET", "POST"])

app/views/commissions/views.py
import traceback

from flask import render_template, url_for, redirect, flash, request

from app.domain.email import send_mail
from app.views.commissions.forms import ContactUsForm
from app.models.commissions import CommissionsPage

def commissions():
    form = ContactUsForm()

    if form.validate_on_submit():
        try:
            send_mail(form.contact.data, form.subject.data, form.body.data, form.references.raw_data)
            flash("Your message was successfully sent!", category="success")
        except Exception:
            flash("Your message wasn't sent. Try again later.", category="danger")
            traceback.print_exc()
        return redirect(url_for("commissions.commissions"))

    content = CommissionsPage.objects.first()
    return render_template(
        "commissions.html",
        content=content,
        form=form
    )

app/views/main/__init__.py
from flask import Blueprint

from app.views.main.views import index

main_bp = Blueprint("main", __name__)

main_bp.add_url_rule("/", "index", index)

app/views/main/views.py
from flask import render_template

from app.models.main import MainPage, SocialMedia

def index():
    content = MainPage.objects.first()
    social_media = SocialMedia.objects.filter(active=True)
    return render_template(
        "index.html", 
        content=content, 
        social_media=social_media
    )

app/views/portfolio/__init__.py
from flask import Blueprint

from app.views.portfolio.views import portfolio

portfolio_bp = Blueprint("portfolio", __name__)

portfolio_bp.add_url_rule("/art", "portfolio", portfolio)

app/views/portfolio/views.py
from flask import render_template

from app.models.portfolio import PortfolioImage, PortfolioPage

def portfolio():
    content = PortfolioPage.objects.first()
    images = PortfolioImage.objects.filter(active=True)
    return render_template(
        "portfolio.html", 
        content=content, 
        images=list(images)
    )

app/templates/admin.html
{% extends "base.html" %}

{% block content %}
<div class="container bg-dark text-light">
    <div class="row">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        {# title - row 1 #}
        <div class="col-sm-12">
            <div class="d-flex justify-content-between pt-3">
                <div>
                    <a class="btn btn-light" href="{{ url_for('main.index') }}">&lt; Back to main</a>
                </div>
                
                <div class="h3 pl-3">
                    Welcome to kitya's admin page, {{ current_user.username }}!
                </div>
            </div>
        </div>
        
        {# main - row 2 #}
        {# settings #}
        <div class="col-sm-8">
            <div class="h5 pt-3">Columns</div>
            <ul class="list-group" id="columns">
                <li class="list-group-item d-flex justify-content-between text-dark px-3">
                    {% for i in (1, 2, 3, 4, 6, 12) %}
                    <div class="form-check">
                        <input class="form-check-input py-0" type="radio" 
                            name="columns" id="columns{{ i }}" value="{{ i }}"
                            {% if i == settings.cols %}checked{% endif %}>
                        <label class="form-check-label py-1" for="columns{{ i }}">{{ i }}</label>
                    </div>
                    {% endfor %}
                    <div class="form-check"><button class="btn btn-success py-0" name="btn-save-cols">Save</button></div>
                </li>
            </ul>

            <div class="h5 pt-3">Albums</div>
            <div class>
                <ul class="list-group" id="albums">
                    {% for album in settings.albums %}
                    <li class="list-group-item px-3" data-albumid="{{ album.album_id }}">
                        <div class="d-flex justify-content-between" role="view">
                            <div class="w-50">
                                <a href="{{ album.permalink }}" target="_blank" class="btn btn-link p-0 pl-1 text-truncate">
                                    {{ album.link_or_album_id }}
                                </a>
                            </div>
                            <div class="btn-group">
                                <button class="btn btn-warning py-0" name="btn-edit-album">Edit</button>
                                <button class="btn btn-danger py-0" name="btn-delete-album">Delete</button>
                            </div>
                        </div>

                        <div class="d-flex justify-content-between" role="edit" style="display: none !important;">
                            <div class="w-50">
                                <input type="text" name="link_or_album_id" class="form-control px-1 py-0" 
                                    placeholder="URL or album ID" style="height: auto;" value="{{ album.link_or_album_id }}">
                            </div>
                            <div class="btn-group">
                                <button class="btn btn-secondary py-0" name="btn-discard-album">Discard</button>
                                <button class="btn btn-success py-0" name="btn-save-album">Save</button>
                            </div>
                        </div>
                    </li>
                    {% endfor %}
                    <li class="list-group-item px-3">
                        <div class="d-flex justify-content-between">
                            <div class="w-50">
                                <input type="text" name="link_or_album_id" class="form-control px-1 py-0" 
                                    placeholder="URL or album ID" style="height: auto;">
                            </div>
                            <div class="btn-group">
                                <button class="btn btn-success py-0" name="btn-add-album">Add</button>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>

            <div class="h5 pt-3">Social media</div>
            <div class>
                <ul class="list-group" id="social-media">
                    {% for media in settings.social_medias %}
                    <li class="list-group-item px-3" data-link="{{ media.link }}">
                        <div class="d-flex justify-content-between" role="view">
                            <div class="pt-1" style="margin-top: 0.3em; margin-bottom: 0.33em;">
                                <img class="rounded mx-auto align-middle" src="{{ media.icon }}" height="32px">
                                <a href="{{ media.link }}" target="_blank" class="btn btn-link py-2 pl-1 align-middle text-truncate"
                                    style="width: calc(75%);">
                                    {{ media.link }}
                                </a>
                            </div>
                            <div class="btn-group-vertical">
                                <button class="btn btn-warning py-0" name="btn-edit-media">Edit</button>
                                <button class="btn btn-danger py-0" name="btn-delete-media">Delete</button>
                            </div>
                        </div>

                        <div class="d-flex justify-content-between" role="edit" style="display: none !important;">
                            <div class="w-50">
                                <input type="text" name="media_icon" class="form-control px-1 py-0" 
                                    placeholder="Link to icon" style="height: auto;" value="{{ media.icon }}">
                                <input type="text" name="media_link" class="form-control px-1 py-0 mt-1" 
                                    placeholder="Link to social media" style="height: auto;" value="{{ media.link }}">
                            </div>
                            <div class="btn-group-vertical">
                                <button class="btn btn-secondary py-0" name="btn-discard-media">Discard</button>
                                <button class="btn btn-success py-0" name="btn-save-media">Save</button>
                            </div>
                        </div>
                    </li>
                    {% endfor %}
                    <li class="list-group-item px-3">
                        <div class="d-flex justify-content-between">
                            <div class="w-50">
                                <input type="text" name="media_icon" class="form-control px-1 py-0" 
                                    placeholder="Link to icon" style="height: auto;">
                                <input type="text" name="media_link" class="form-control px-1 py-0 mt-1" 
                                    placeholder="Link to social media" style="height: auto;">
                            </div>
                            <div class="btn-group">
                                <button class="btn btn-success py-0" name="btn-add-media">Add</button>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>

            <div class="h5 pt-3">Access</div>
            <div class>
                <ul class="list-group text-dark" id="access">
                    {% for admin in settings.admins %}
                    <li class="list-group-item px-3" data-username="{{ admin.username }}">
                        <div class="d-flex justify-content-between" role="view">
                            <div class="m-1">{{ admin.username }} 
                                {% if admin.is_owner %}<span class="badge badge-success" style="cursor: pointer"
                                data-toggle="tooltip" title="User with this credentials can add, edit and delete credentials.">
                                owner</span>
                                {% else %}<span class="badge badge-info" style="cursor: pointer"
                                data-toggle="tooltip" title="User with this credentials can not add, edit and delete credentials.">
                                admin</span>
                                {% endif %}
                                {% if admin.disabled %}<span class="badge badge-secondary" style="cursor: pointer"
                                data-toggle="tooltip" title="User with this credentials can not use admin page.">
                                disabled</span>{% endif %}
                            </div>
                            <div class="btn-group">
                                <button class="btn btn-warning py-0" name="btn-edit-admin"
                                {% if not current_user.is_owner %}disabled{% endif %}>Edit</button>
                                <button class="btn btn-danger py-0" name="btn-delete-admin"
                                {% if not current_user.is_owner %}disabled{% endif %}>Delete</button>
                            </div>
                        </div>

                        <div class="d-flex justify-content-between" role="edit" style="display: none !important;">
                            <div class="row">
                                <div class="col">
                                    <input type="password" name="old_password" class="form-control px-1 py-0" 
                                    placeholder="Old password" style="height: auto;">
                                </div>
                                <div class="col">
                                    <input type="password" name="new_password" class="form-control px-1 py-0" 
                                    placeholder="New password" style="height: auto;">
                                </div>
                                <div class="col">
                                    <div class="form-check">
                                        <input type="checkbox" class="form-check-input py-0" name="disabled"
                                        {% if admin.disabled %}checked{% endif %}>
                                        <label class="form-check-label py-1" for="disabled">Disabled</label>
                                    </div>
                                </div>
                            </div>
                            <div class="btn-group">
                                <button class="btn btn-secondary py-0" name="btn-discard-admin">Discard</button>
                                <button class="btn btn-success py-0" name="btn-save-admin">Save</button>
                            </div>
                        </div>
                    </li>

                    {% endfor %}
                    <li class="list-group-item px-3">
                        <div class="d-flex justify-content-between">
                            <div class="row">
                                <div class="col">
                                    <input type="text" name="username" class="form-control px-1 py-0" 
                                    placeholder="Username" style="height: auto;"
                                    {% if not current_user.is_owner %}disabled{% endif %}>
                                </div>
                                <div class="col">
                                    <input type="password" name="password" class="form-control px-1 py-0" 
                                    placeholder="Password" style="height: auto;"
                                    {% if not current_user.is_owner %}disabled{% endif %}>
                                </div>
                                <div class="col">
                                    <div class="form-check">
                                        <input type="checkbox" class="form-check-input py-0" name="disabled">
                                        <label class="form-check-label py-1" for="disabled"
                                        {% if not current_user.is_owner %}disabled{% endif %}>Disabled</label>
                                    </div>
                                </div>
                            </div>
                            <div class="btn-group">
                                <button class="btn btn-success py-0" name="btn-add-admin"
                                {% if not current_user.is_owner %}disabled{% endif %}>Add</button>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>

        </div>

        {# info #}
        <div class="col-sm-4">
            <div class="h5 pt-3">Last seen</div>
            <ul class="list-group">
                {% for admin in settings.admins|sort(reverse=True, attribute="last_login") %}
                <li class="list-group-item 
                {% if not admin.is_owner %}list-group-item-light text-dark{% endif %}
                {% if admin.is_owner %}list-group-item-primary{% endif %}
                {% if admin.disabled %}disabled{% endif %}
                ">
                    <div class="d-flex justify-content-between">
                        <p>{{ admin.username }}{% if admin.disabled %}<span class="text-secondary">(disabled)</span>{% endif %}</p>
                        <p>{{ moment(admin.last_login).fromNow() }}</p>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>

        {# spinner - row 3 #}
        <div class="col-sm-12 py-2">
            <div class="d-flex justify-content-center">
                <div class="spinner-border" id="spinner" role="status" style="opacity: 0;">
                    <span class="sr-only">Loading...</span>
                </div>
            </div>
        </div>

        {# footer - row 4 (maybe) #}
    </div>
</div>
{% endblock %}

app/templates/base.html
{% extends "bootstrap/base.html" %}
{% block html_attribs %}
lang="en"
{% endblock %}
{% block head %}
{{ super() }}
{{ moment.include_moment() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
{% endblock %}
{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='mastfoot.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
{% endblock %}
{% block scripts %}
{{ super() }}
<script src="{{ url_for('static', filename='script.js') }}"></script>
{% endblock %}

app/templates/commissions.html
{% extends "base.html" %}
{% block content %}
<body class="text-center" style="
        background-size: cover;
        background-repeat: no-repeat;
        {% if content.background_image %}
        background-image: url({{ content.background_image }})
        {% endif %}">
    <div class="cover-container d-flex w-100 h-100 py-3 mx-auto flex-column">
        <header class="masthead mb-auto">
            {% include "include/nav.html" %}
        </header>
        <main class="inner cover">
            <p class="lead">
                {{ content.body }}
            </p>
            <p class="lead">
                {% from "macro/render_field.html" import render_field %}
                {% from "macro/render_file_upload.html" import render_file_upload %}
                <form method="POST" action="{{ url_for('commissions.commissions') }}" class="form" enctype="multipart/form-data">
                    {{ form.csrf_token }}
                    {{ render_field(form.contact, class="form-control", placeholder="Your email") }}
                    {{ render_field(form.subject, class="form-control", placeholder="Summary") }}
                    {{ render_field(form.body, class="form-control", placeholder="Description") }}
                    {{ render_file_upload(form.references, class="upload-files-button", accept="image/*", multiple=True) }}
                    {{ form.submit(class="btn btn-lg btn-secondary") }}
                </form>
            </p>
            {% include "include/flash.html" %}
        </main>
        <footer class="mastfoot mt-auto">
            <div class="justify-content-center">
            </div>
        </footer>
    </div>
</body>
{% endblock %}

app/templates/include/flash.html
<div class="fixed-bottom cover-container px-3" style="left: 0; right: 0; margin: auto">
    {% for category, message in get_flashed_messages(with_categories=True) %}
    <div class="alert alert-{{category}}">
        {{ message }}
        <button type="button" class="close" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
</div>

app/templates/include/image.html
<div class="img-thumbnail mb-2">
    <img class="img" src="{{ image.thumbnail_url or image.url }}" style="width: 100%;">
    {% if image.name %}
        <p class="m-0 p-0 w-100 text-dark">{{ image.name }}</p>
    {% endif %}
</div>

app/templates/include/nav.html
<div class="inner">
    <h3 class="masthead-brand">Kitya</h3>
    <nav class="nav nav-masthead justify-content-center">
        <a class="nav-link {% if request.url_rule.endpoint == 'main.index' %}active{% endif %}" 
                href="{{ url_for('main.index') }}">Home</a>
        <a class="nav-link {% if request.url_rule.endpoint == 'portfolio.portfolio' %}active{% endif %}" 
                href="{{ url_for('portfolio.portfolio') }}">Portfolio</a>
        <a class="nav-link {% if request.url_rule.endpoint == 'commissions.commissions' %}active{% endif %}" 
                href="{{ url_for('commissions.commissions') }}">Commissions</a>
        <a class="nav-link {% if request.url_rule.endpoint == '#' %}active{% endif %}" 
                href="#">Prints</a>
    </nav>
</div>

app/templates/index.html
{% extends "base.html" %}
{% block content %}
<body class="text-center" style="
        background-size: cover;
        background-repeat: no-repeat;
        {% if content.background_image %}
        background-image: url({{ content.background_image }})
        {% endif %}">
    <div class="cover-container d-flex w-100 h-100 py-3 mx-auto flex-column">
        <header class="masthead mb-auto">
            {% include "include/nav.html" %}
        </header>
        <main class="inner cover">
            <h1 class="cover-heading">
                {{ content.header }}
            </h1>
            <p class="lead">
                {{ content.body }}
            </p>
            <p class="lead">
                <a href="{{ url_for('portfolio.portfolio') }}" class="btn btn-lg btn-secondary">{{ content.button_text }}</a>
            </p>
        </main>
        <footer class="mastfoot mt-auto">
            <div class="justify-content-center">
                {% for media in social_media %}
                <a href="{{ media.link }}" style="text-decoration: none;" class="px-2" target="_blank">
                    <img style="height: 1.25em; width: 1.25em;" src="{{ media.icon }}" class="img rounded">
                    <span class="pl-1">{{ media.name }}</span>
                </a>
                {% endfor %}
            </div>
        </footer>
    </div>
</body>
{% endblock %}

app/templates/macro/render_field.html
{% macro render_field(field) %}
    <div class="form-group row mb-2">
        <div class="col-sm-12">
            {{ field(**kwargs)|safe }}
        </div>
        {% if field.errors %}
        {% for error in field.errors %}
        <div class="invalid-feedback" style="display: block;">
            {{ error }}
        </div>
        {% endfor %}
        {% endif %}
    </div>
{% endmacro %}

app/templates/macro/render_file_upload.html
{% macro render_file_upload(field) %}
    <div class="form-group row mb-2">
        <div class="col-sm-12">
            {{ field.label(class="btn btn-sm btn-info btn-block") }}
            {% if field.errors %}
                {% for error in field.errors %}
                <div class="invalid-feedback" style="display: block;">
                    {{ error }}
                </div>
                {% endfor %}
            {% endif %}
            <p class="h6">Send images up to 2 MB</p>
        </div>
        {{ field(**kwargs)|safe }}
    </div>
{% endmacro %}

app/templates/portfolio.html
{% extends "base.html" %}
{% block content %}
<body class="text-center" style="
        background-size: cover;
        background-repeat: no-repeat;
        {% if content.background_image %}
        background-image: url({{ content.background_image }})
        {% endif %}">
    <div class="cover-container d-flex w-100 h-100 pt-3 mx-auto flex-column">
        <header class="masthead">
            {% include "include/nav.html" %}
        </header>
        <main class="inner cover custom-scrollbar" style="height: calc(100% - 36px); overflow-y: scroll;">
            <div class="inner">
                {% if content.body %}
                    <p class="lead">{{ content.body }}</p>
                {% endif %}
            </div>
            <div class="row">
                <div class="col-6 m-0 p-0 pr-1">
                    {% for image in images[::2] %}
                        {% include "include/image.html" %}
                    {% endfor %}
                </div>
                <div class="col-6 m-0 p-0 pl-1">
                    {% for image in images[1::2] %}
                        {% include "include/image.html" %}
                    {% endfor %}
                </div>
            </div>
        </main>
        <footer class="mastfoot mt-auto">
            <div class="justify-content-center">
            </div>
        </footer>
    </div>
</body>
{% endblock %}